# Generated by Django 5.0 on 2024-01-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symphony_Counting_Model',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('countedInteractions', models.IntegerField(default=0)),
            ],
        ),
    ]
