# Generated by Django 5.0 on 2024-01-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symphony_count', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symphony_counting_model',
            name='isTrending',
            field=models.BooleanField(default=False),
        ),
    ]
